import json

import xml.etree.ElementTree as ElementTree

# tree = ElementTree.parse('data.xml')
# xml_data = tree.getroot()
# xmlstr = ElementTree.tostring(xml_data, encoding='ISO-8859-1', method='xml')
# data_dict = dict(xmltodict.parse(xmlstr))
# obj2 = parser.parse("20221026").date()
# print(json.dumps(data_dict))
# print(obj2)

# from datetime import datetime
#
# date = datetime.today().date()
#
# print(date)
#
# dict = xmltodict.parse(ElementTree.tostring(ElementTree.parse('data.xml').getroot()))
dataa = ("""
<stanID>1234576</stanID>
<localDateTime>20220829</localDateTime>
<channelID>TR</channelID>
<cifID>123</cifID>
<custName>abc</custName>
<tradeNumber>123</tradeNumber>
<tradeType>Spot</tradeType>
<tradedate>20220829</tradedate>
<description>qwe wewqe </description>
<status>00</status>
<portfolio>fdfsdfd</portfolio>
<companyBook>VN0011131</companyBook>
<company>VN0011131</company>
<channel>IB</channel>
<purpose>abc</purpose>
<userInput>qc_user004</userInput>
<depUserInput>ID8560</depUserInput>
<userApprove>qc_user005</userApprove>
<depUserApprove>ID11237</depUserApprove>
<trade1>
<valueDate>20220829</valueDate>
<creditAccount>060135876758</creditAccount>
<debitAccount>0602342343</debitAccount>
<currencyBuy>VND</currencyBuy>
<currencySell>USD</currencySell>
<amountBuy>23213</amountBuy>
<amountSell>234234</amountSell>
<customerRate>2</customerRate>
<internalRate>1.5</internalRate>
</trade1>
<trade2>
<valueDate>20220829</valueDate>
<creditAccount>060135876758</creditAccount>
<debitAccount>0602342343</debitAccount>
<currencyBuy>VND</currencyBuy>
<currencySell>USD</currencySell>
<amountBuy>23213</amountBuy>
<amountSell>234234</amountSell>
<customerRate>2</customerRate>
<internalRate>1.5</internalRate>
</trade2>

""")

data2 = ("""
<MESSAGE>
  <TYPE>UPDATE_SETTLEMENT</TYPE>
  <VERSION>1.0</VERSION>
  <TIME>2022-11-25 03:26:32</TIME>
  <SOURCE>AMBA_OPS_SACOM_BUILD22</SOURCE>
  <LOCALE>C</LOCALE>
  <SETTLEMENT>
    <RECORD_TYPE>Settlement</RECORD_TYPE>
    <SEQNBR>15</SEQNBR>
    <CREAT_TIME>2022-11-25 10:22:08</CREAT_TIME>
    <CREAT_USRNBR>14</CREAT_USRNBR>
    <CREAT_USRNBR.USERID>ATS_SETTLE</CREAT_USRNBR.USERID>
    <UPDAT_TIME>2022-11-25 10:26:30</UPDAT_TIME>
    <UPDAT_USRNBR>20</UPDAT_USRNBR>
    <UPDAT_USRNBR.USERID>FMAINTENANCE</UPDAT_USRNBR.USERID>
    <UPDAT_USRNBR>14</UPDAT_USRNBR>
    <UPDAT_USRNBR.USERID>ATS_SETTLE</UPDAT_USRNBR.USERID>
    <PROTECTION>W:R,O:RWD,G:RWD,U:RWD</PROTECTION>
    <OWNER_USRNBR>20</OWNER_USRNBR>
    <OWNER_USRNBR.USERID>FMAINTENANCE</OWNER_USRNBR.USERID>
    <FOUR_EYE_ON>No</FOUR_EYE_ON>
    <AUTHORIZER_USRNBR>0</AUTHORIZER_USRNBR>
    <VERSION_ID>1</VERSION_ID>
    <VERSION_ID>0</VERSION_ID>
    <TRDNBR>13029</TRDNBR>
    <TRDNBR.BO_TRDNBR>6</TRDNBR.BO_TRDNBR>
    <TRDNBR.OPTIONAL_KEY></TRDNBR.OPTIONAL_KEY>
    <CFWNBR>0</CFWNBR>
    <DIVIDEND_SEQNBR>0</DIVIDEND_SEQNBR>
    <PAYNBR>0</PAYNBR>
    <AMOUNT>-100000</AMOUNT>
    <CURR>16</CURR>
    <CURR.INSID>VND</CURR.INSID>
    <CURR.EXTERN_ID1></CURR.EXTERN_ID1>
    <CURR.EXTERN_ID2></CURR.EXTERN_ID2>
    <CURR.ISIN></CURR.ISIN>
    <VALUE_DAY>2022-11-28</VALUE_DAY>
    <TO_PRFNBR>0</TO_PRFNBR>
    <FROM_PRFNBR>18</FROM_PRFNBR>
    <FROM_PRFNBR.PRFID>FX_TRADING_SPOT</FROM_PRFNBR.PRFID>
    <FROM_PRFNBR.ASSINF>FX_TRADING_SPOT</FROM_PRFNBR.ASSINF>
    <SETTLEINSTRUCTION_SEQNBR>0</SETTLEINSTRUCTION_SEQNBR>
    <STATUS>Released</STATUS>
    <STATUS>Authorised</STATUS>
    <TYPE>Premium</TYPE>
    <DELIVERY_TYPE>Delivery Free of Payment</DELIVERY_TYPE>
    <ACQUIRER_PTYID>Acquirer 1</ACQUIRER_PTYID>
    <ACQUIRER_ACCOUNT>3002</ACQUIRER_ACCOUNT>
    <ACQUIRER_ACCNAME>AQ1_USD_CHASUS33_SPayGatw</ACQUIRER_ACCNAME>
    <ACQUIRER_ACCOUNT_NETWORK_NAME>SacomPaymentGateway</ACQUIRER_ACCOUNT_NETWORK_NAME>
    <PARTY_PTYID>Counterparty 1</PARTY_PTYID>
    <PARTY_ACCOUNT>1001</PARTY_ACCOUNT>
    <PARTY_ACCNAME>CP1_USD_CHASUS33_SPayGatw</PARTY_ACCNAME>
    <PARTY_ACCOUNT_NETWORK_NAME>SacomPaymentGateway</PARTY_ACCOUNT_NETWORK_NAME>
    <TEXT></TEXT>
    <STATUS_EXPLANATION>0</STATUS_EXPLANATION>
    <NETTING_RULE_SEQNBR>0</NETTING_RULE_SEQNBR>
    <MANUAL_MATCH>No</MANUAL_MATCH>
    <POST_SETTLE_ACTION>No</POST_SETTLE_ACTION>
    <SEC_INSADDR>0</SEC_INSADDR>
    <DIARY>751</DIARY>
    <DIARY.NEXT_SEQNBR>0</DIARY.NEXT_SEQNBR>
    <DIARY.TYPE>Settlement diary</DIARY.TYPE>
    <DIARY.USRNBR>0</DIARY.USRNBR>
    <DIARY.NAME>Diary738849.12390490</DIARY.NAME>
    <DIARY>0</DIARY>
    <ORG_SEC_NOM>0</ORG_SEC_NOM>
    <AGGREGATE>0</AGGREGATE>
    <AGGREGATE_SEQNBR>0</AGGREGATE_SEQNBR>
    <ARCHIVE_STATUS>0</ARCHIVE_STATUS>
    <PRIMARY_ISSUANCE>No</PRIMARY_ISSUANCE>
    <SETTLED_AMOUNT>0</SETTLED_AMOUNT>
    <NOTIFICATION_DAY>0000-01-01</NOTIFICATION_DAY>
    <RESTRICT_NET>No</RESTRICT_NET>
    <REF_PAYNBR>0</REF_PAYNBR>
    <COUNTERPARTY_PTYNBR>19</COUNTERPARTY_PTYNBR>
    <COUNTERPARTY_PTYNBR.PTYID>Counterparty 1</COUNTERPARTY_PTYNBR.PTYID>
    <COUNTERPARTY_PTYNBR.RED_CODE></COUNTERPARTY_PTYNBR.RED_CODE>
    <COUNTERPARTY_PTYNBR.PTYID2></COUNTERPARTY_PTYNBR.PTYID2>
    <COUNTERPARTY_PTYNBR.LEGAL_ENTITY_ID></COUNTERPARTY_PTYNBR.LEGAL_ENTITY_ID>
    <ACQUIRER_PTYNBR>13</ACQUIRER_PTYNBR>
    <ACQUIRER_PTYNBR.PTYID>Acquirer 1</ACQUIRER_PTYNBR.PTYID>
    <ACQUIRER_PTYNBR.RED_CODE></ACQUIRER_PTYNBR.RED_CODE>
    <ACQUIRER_PTYNBR.PTYID2></ACQUIRER_PTYNBR.PTYID2>
    <ACQUIRER_PTYNBR.LEGAL_ENTITY_ID></ACQUIRER_PTYNBR.LEGAL_ENTITY_ID>
    <THEIR_CORR_ACCOUNT>1001</THEIR_CORR_ACCOUNT>
    <THEIR_CORR_ACCOUNT2>1002</THEIR_CORR_ACCOUNT2>
    <THEIR_CORR_ACCOUNT3></THEIR_CORR_ACCOUNT3>
    <THEIR_CORR_ACCOUNT4></THEIR_CORR_ACCOUNT4>
    <THEIR_CORR_ACCOUNT4></THEIR_CORR_ACCOUNT5>
    <THEIR_CORR_ACCOUNT6></THEIR_CORR_ACCOUNT6>
    <THEIR_CORR_BANK>Correspondent Bank 1 (J.P.MORGAN US)</THEIR_CORR_BANK>
    <THEIR_CORR_BANK2>Correspondent Bank 2 (DEUTSCHE BANK NY)</THEIR_CORR_BANK2>
    <THEIR_CORR_BANK3></THEIR_CORR_BANK3>
    <THEIR_CORR_BANK4></THEIR_CORR_BANK4>
    <THEIR_CORR_BANK5></THEIR_CORR_BANK5>
    <SPLIT_PARENT_SEQNBR>0</SPLIT_PARENT_SEQNBR>
    <PARENT_SEQNBR>0</PARENT_SEQNBR>
    <RELATION_TYPE>None</RELATION_TYPE>
    <SPLIT_TYPE_CHLNBR>0</SPLIT_TYPE_CHLNBR>
    <SETTLED_DAY>0000-01-01</SETTLED_DAY>
    <ACCOUNTING_NOTIFICATION_DAY>0000-01-01</ACCOUNTING_NOTIFICATION_DAY>
    <ACCOUNTING_SETTLED_DAY>0000-01-01</ACCOUNTING_SETTLED_DAY>
    <YOUR_REF></YOUR_REF>
    <STATE_CHART_SEQNBR>0</STATE_CHART_SEQNBR>
    <PROCESS_STATUS_CHLNBR>0</PROCESS_STATUS_CHLNBR>
    <PARTIAL_SETTLEMENT_TYPE>None</PARTIAL_SETTLEMENT_TYPE>
    <CORRECTION_SETTLEMENT_SEQNBR>0</CORRECTION_SETTLEMENT_SEQNBR>
    <PARTIAL_PARENT_SEQNBR>0</PARTIAL_PARENT_SEQNBR>
    <PAIR_OFF_PARENT_SEQNBR>0</PAIR_OFF_PARENT_SEQNBR>
    <CREATED_FROM_PAIR_OFF_SEQNBR>0</CREATED_FROM_PAIR_OFF_SEQNBR>
    <ACQUIRER_ACCOUNT_REF_SEQNBR>35</ACQUIRER_ACCOUNT_REF_SEQNBR>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR>13</ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID>Acquirer 1</ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.RED_CODE></ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.RED_CODE>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID2></ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID2>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.LEGAL_ENTITY_ID></ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.LEGAL_ENTITY_ID>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.NAME>AQ1_USD_CHASUS33_SPayGatw</ACQUIRER_ACCOUNT_REF_SEQNBR.NAME>
    <PARTY_ACCOUNT_REF_SEQNBR>34</PARTY_ACCOUNT_REF_SEQNBR>
    <PARTY_ACCOUNT_REF_SEQNBR.PTYNBR>19</PARTY_ACCOUNT_REF_SEQNBR.PTYNBR>
    <PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID>Counterparty 1</PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID>
    <PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.RED_CODE></PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.RED_CODE>
    <PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID2></PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID2>
    <PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.LEGAL_ENTITY_ID></PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.LEGAL_ENTITY_ID>
    <PARTY_ACCOUNT_REF_SEQNBR.NAME>CP1_USD_CHASUS33_SPayGatw</PARTY_ACCOUNT_REF_SEQNBR.NAME>
    <BILLING_INFORMATION_SEQNBR>0</BILLING_INFORMATION_SEQNBR>
  </SETTLEMENT>
</MESSAGE>
 """).replace('</MESSAGE>', """</MESSAGE>
</root>""").replace('<MESSAGE>', """<root>
<MESSAGE>""")
data3 = ("""
<MESSAGE>
  <TYPE>UPDATE_SETTLEMENT</TYPE>
  <VERSION>1.0</VERSION>
  <TIME>2022-11-25 03:26:32</TIME>
  <SOURCE>AMBA_OPS_SACOM_BUILD22</SOURCE>
  <LOCALE>C</LOCALE>
  <!SETTLEMENT>
    <RECORD_TYPE>Settlement</RECORD_TYPE>
    <SEQNBR>15</SEQNBR>
    <CREAT_TIME>2022-11-25 10:22:08</CREAT_TIME>
    <CREAT_USRNBR>14</CREAT_USRNBR>
    <CREAT_USRNBR.USERID>ATS_SETTLE</CREAT_USRNBR.USERID>
    <UPDAT_TIME>2022-11-25 10:26:30</UPDAT_TIME>
    <!UPDAT_TIME>2022-11-25 10:22:08</!UPDAT_TIME>
    <UPDAT_USRNBR>20</UPDAT_USRNBR>
    <UPDAT_USRNBR.USERID>FMAINTENANCE</UPDAT_USRNBR.USERID>
    <!UPDAT_USRNBR>14</!UPDAT_USRNBR>
    <!UPDAT_USRNBR.USERID>ATS_SETTLE</!UPDAT_USRNBR.USERID>
    <PROTECTION>W:R,O:RWD,G:RWD,U:RWD</PROTECTION>
    <OWNER_USRNBR>20</OWNER_USRNBR>
    <OWNER_USRNBR.USERID>FMAINTENANCE</OWNER_USRNBR.USERID>
    <FOUR_EYE_ON>No</FOUR_EYE_ON>
    <AUTHORIZER_USRNBR>0</AUTHORIZER_USRNBR>
    <VERSION_ID>1</VERSION_ID>
    <!VERSION_ID>0</!VERSION_ID>
    <TRDNBR>13029</TRDNBR>
    <TRDNBR.BO_TRDNBR>6</TRDNBR.BO_TRDNBR>
    <TRDNBR.OPTIONAL_KEY></TRDNBR.OPTIONAL_KEY>
    <CFWNBR>0</CFWNBR>
    <DIVIDEND_SEQNBR>0</DIVIDEND_SEQNBR>
    <PAYNBR>0</PAYNBR>
    <AMOUNT>-100000</AMOUNT>
    <CURR>16</CURR>
    <CURR.INSID>VND</CURR.INSID>
    <CURR.EXTERN_ID1></CURR.EXTERN_ID1>
    <CURR.EXTERN_ID2></CURR.EXTERN_ID2>
    <CURR.ISIN></CURR.ISIN>
    <VALUE_DAY>2022-11-28</VALUE_DAY>
    <TO_PRFNBR>0</TO_PRFNBR>
    <FROM_PRFNBR>18</FROM_PRFNBR>
    <FROM_PRFNBR.PRFID>FX_TRADING_SPOT</FROM_PRFNBR.PRFID>
    <FROM_PRFNBR.ASSINF>FX_TRADING_SPOT</FROM_PRFNBR.ASSINF>
    <SETTLEINSTRUCTION_SEQNBR>0</SETTLEINSTRUCTION_SEQNBR>
    <STATUS>Released</STATUS>
    <!STATUS>Authorised</!STATUS>
    <TYPE>Premium</TYPE>
    <DELIVERY_TYPE>Delivery Free of Payment</DELIVERY_TYPE>
    <ACQUIRER_PTYID>Acquirer 1</ACQUIRER_PTYID>
    <ACQUIRER_ACCOUNT>3002</ACQUIRER_ACCOUNT>
    <ACQUIRER_ACCNAME>AQ1_USD_CHASUS33_SPayGatw</ACQUIRER_ACCNAME>
    <ACQUIRER_ACCOUNT_NETWORK_NAME>SacomPaymentGateway</ACQUIRER_ACCOUNT_NETWORK_NAME>
    <PARTY_PTYID>Counterparty 1</PARTY_PTYID>
    <PARTY_ACCOUNT>1001</PARTY_ACCOUNT>
    <PARTY_ACCNAME>CP1_USD_CHASUS33_SPayGatw</PARTY_ACCNAME>
    <PARTY_ACCOUNT_NETWORK_NAME>SacomPaymentGateway</PARTY_ACCOUNT_NETWORK_NAME>
    <TEXT></TEXT>
    <STATUS_EXPLANATION>0</STATUS_EXPLANATION>
    <NETTING_RULE_SEQNBR>0</NETTING_RULE_SEQNBR>
    <MANUAL_MATCH>No</MANUAL_MATCH>
    <POST_SETTLE_ACTION>No</POST_SETTLE_ACTION>
    <SEC_INSADDR>0</SEC_INSADDR>
    <DIARY>751</DIARY>
    <DIARY.NEXT_SEQNBR>0</DIARY.NEXT_SEQNBR>
    <DIARY.TYPE>Settlement diary</DIARY.TYPE>
    <DIARY.USRNBR>0</DIARY.USRNBR>
    <DIARY.NAME>Diary738849.12390490</DIARY.NAME>
    <!DIARY>0</!DIARY>
    <ORG_SEC_NOM>0</ORG_SEC_NOM>
    <AGGREGATE>0</AGGREGATE>
    <AGGREGATE_SEQNBR>0</AGGREGATE_SEQNBR>
    <ARCHIVE_STATUS>0</ARCHIVE_STATUS>
    <PRIMARY_ISSUANCE>No</PRIMARY_ISSUANCE>
    <SETTLED_AMOUNT>0</SETTLED_AMOUNT>
    <NOTIFICATION_DAY>0000-01-01</NOTIFICATION_DAY>
    <RESTRICT_NET>No</RESTRICT_NET>
    <REF_PAYNBR>0</REF_PAYNBR>
    <COUNTERPARTY_PTYNBR>19</COUNTERPARTY_PTYNBR>
    <COUNTERPARTY_PTYNBR.PTYID>Counterparty 1</COUNTERPARTY_PTYNBR.PTYID>
    <COUNTERPARTY_PTYNBR.RED_CODE></COUNTERPARTY_PTYNBR.RED_CODE>
    <COUNTERPARTY_PTYNBR.PTYID2></COUNTERPARTY_PTYNBR.PTYID2>
    <COUNTERPARTY_PTYNBR.LEGAL_ENTITY_ID></COUNTERPARTY_PTYNBR.LEGAL_ENTITY_ID>
    <ACQUIRER_PTYNBR>13</ACQUIRER_PTYNBR>
    <ACQUIRER_PTYNBR.PTYID>Acquirer 1</ACQUIRER_PTYNBR.PTYID>
    <ACQUIRER_PTYNBR.RED_CODE></ACQUIRER_PTYNBR.RED_CODE>
    <ACQUIRER_PTYNBR.PTYID2></ACQUIRER_PTYNBR.PTYID2>
    <ACQUIRER_PTYNBR.LEGAL_ENTITY_ID></ACQUIRER_PTYNBR.LEGAL_ENTITY_ID>
    <THEIR_CORR_ACCOUNT>1001</THEIR_CORR_ACCOUNT>
    <THEIR_CORR_ACCOUNT2>1002</THEIR_CORR_ACCOUNT2>
    <THEIR_CORR_ACCOUNT3></THEIR_CORR_ACCOUNT3>
    <THEIR_CORR_ACCOUNT4></THEIR_CORR_ACCOUNT4>
    <THEIR_CORR_ACCOUNT5></THEIR_CORR_ACCOUNT5>
    <THEIR_CORR_BANK>Correspondent Bank 1 (J.P.MORGAN US)</THEIR_CORR_BANK>
    <THEIR_CORR_BANK2>Correspondent Bank 2 (DEUTSCHE BANK NY)</THEIR_CORR_BANK2>
    <THEIR_CORR_BANK3></THEIR_CORR_BANK3>
    <THEIR_CORR_BANK4></THEIR_CORR_BANK4>
    <THEIR_CORR_BANK5></THEIR_CORR_BANK5>
    <SPLIT_PARENT_SEQNBR>0</SPLIT_PARENT_SEQNBR>
    <PARENT_SEQNBR>0</PARENT_SEQNBR>
    <RELATION_TYPE>None</RELATION_TYPE>
    <SPLIT_TYPE_CHLNBR>0</SPLIT_TYPE_CHLNBR>
    <SETTLED_DAY>0000-01-01</SETTLED_DAY>
    <ACCOUNTING_NOTIFICATION_DAY>0000-01-01</ACCOUNTING_NOTIFICATION_DAY>
    <ACCOUNTING_SETTLED_DAY>0000-01-01</ACCOUNTING_SETTLED_DAY>
    <YOUR_REF></YOUR_REF>
    <STATE_CHART_SEQNBR>0</STATE_CHART_SEQNBR>
    <PROCESS_STATUS_CHLNBR>0</PROCESS_STATUS_CHLNBR>
    <PARTIAL_SETTLEMENT_TYPE>None</PARTIAL_SETTLEMENT_TYPE>
    <CORRECTION_SETTLEMENT_SEQNBR>0</CORRECTION_SETTLEMENT_SEQNBR>
    <PARTIAL_PARENT_SEQNBR>0</PARTIAL_PARENT_SEQNBR>
    <PAIR_OFF_PARENT_SEQNBR>0</PAIR_OFF_PARENT_SEQNBR>
    <CREATED_FROM_PAIR_OFF_SEQNBR>0</CREATED_FROM_PAIR_OFF_SEQNBR>
    <ACQUIRER_ACCOUNT_REF_SEQNBR>35</ACQUIRER_ACCOUNT_REF_SEQNBR>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR>13</ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID>Acquirer 1</ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.RED_CODE></ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.RED_CODE>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID2></ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID2>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.LEGAL_ENTITY_ID></ACQUIRER_ACCOUNT_REF_SEQNBR.PTYNBR.LEGAL_ENTITY_ID>
    <ACQUIRER_ACCOUNT_REF_SEQNBR.NAME>AQ1_USD_CHASUS33_SPayGatw</ACQUIRER_ACCOUNT_REF_SEQNBR.NAME>
    <PARTY_ACCOUNT_REF_SEQNBR>34</PARTY_ACCOUNT_REF_SEQNBR>
    <PARTY_ACCOUNT_REF_SEQNBR.PTYNBR>19</PARTY_ACCOUNT_REF_SEQNBR.PTYNBR>
    <PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID>Counterparty 1</PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID>
    <PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.RED_CODE></PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.RED_CODE>
    <PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID2></PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.PTYID2>
    <PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.LEGAL_ENTITY_ID></PARTY_ACCOUNT_REF_SEQNBR.PTYNBR.LEGAL_ENTITY_ID>
    <PARTY_ACCOUNT_REF_SEQNBR.NAME>CP1_USD_CHASUS33_SPayGatw</PARTY_ACCOUNT_REF_SEQNBR.NAME>
    <BILLING_INFORMATION_SEQNBR>0</BILLING_INFORMATION_SEQNBR>
    <BILLING_INFORMATION_SEQNBR>0</BILLING_INFORMATION_SEQNBR>
  </!SETTLEMENT>
</MESSAGE>
 """)

data = ("""
[MESSAGE]
    TYPE=UPDATE_TRADE
    VERSION=1.0
    TIME=1999-03-10 11:30:11
    SOURCE=ADS_PROD
    [TRADE]
      TRDNBR=1001917
      INSADDR.INSID=DEM/BND/128000
      INSADDR.EXTERN_ID1=ext128k
      ACQUIRE_DAY=1998-03-12
      ACQUIRER_PTYNBR.PTYID=Bond Nat Desk
      CURR.INSID=DEM
      VALUE_DAY=1998-03-12
      TIME=1998-03-10 12:29:06
      QUANTITY=5
      PRICE=99.78
      PREMIUM=-5.205389E+06
      FEE=100
      STATUS=FO Confirmed
      COUNTERPARTY_PTYNBR.PTYID=Investor
      TRADER_USRNBR.USERID=ATLAS
      TYPE=Normal
      BROKER_PTYNBR.PTYID=Broker A
      DOCUMENT_TYPE_CHLNBR.ENTRY=ISDA
      DOCUMENT_TYPE_CHLNBR.LIST=Standard Document
      TEXT1=TRD17
      CONTRACT_TRDNBR=1001917
      EXECUTION_TIME=1998-03-10 12:29:06
      [ADDITIONALINFO]
         ADDINF_SPECNBR.FIELD_NAME=Break Date
         VALUE=1999-03-10
      [/ADDITIONALINFO]
    [/TRADE]
[/MESSAGE]
""").replace('[/MESSAGE]', """[/MESSAGE]
[/root]""").replace('[MESSAGE]', """[root]
[MESSAGE]""")

# import pandas as pd
# aa = pd.read_xml(data2)
# print(aa)


json_file = """{
  "Channel": "T24",
  "stanID": "221026174350_638024030302438607_phitestlan3",
  "localDateTime": 20221027174409,
  "Data": [
    {
      "MuaTM": "",
      "MuaCK": 23200,
      "BanTM": "",
      "BanCK": 23600,
      "LoaiTien": "USD",
      "Nhom": ""
    },
    {
      "MuaTM": 23270,
      "MuaCK": "",
      "BanTM": 23450,
      "BanCK": "",
      "LoaiTien": "USD",
      "Nhom": "USDSMALL2"
    },
    {
      "MuaTM": 23270,
      "MuaCK": "",
      "BanTM": 23440,
      "BanCK": "",
      "LoaiTien": "USD",
      "Nhom": "USD"
    },
    {
      "MuaTM": 23300,
      "MuaCK": "",
      "BanTM": 23400,
      "BanCK": "",
      "LoaiTien": "USD",
      "Nhom": "USDSMALL3"
    },
    {
      "MuaTM": 14808,
      "MuaCK": 14708,
      "BanTM": 14849,
      "BanCK": 15049,
      "LoaiTien": "AUD",
      "Nhom": ""
    },
    {
      "MuaTM": 6580000,
      "MuaCK": "",
      "BanTM": 6580000,
      "BanCK": "",
      "LoaiTien": "XAU",
      "Nhom": ""
    },
    {
      "MuaTM": 24009,
      "MuaCK": 23889,
      "BanTM": 24073,
      "BanCK": 24293,
      "LoaiTien": "EUR",
      "Nhom": ""
    },
    {
      "MuaTM": 1,
      "MuaCK": 159,
      "BanTM": 1,
      "BanCK": 174,
      "LoaiTien": "JPY",
      "Nhom": ""
    },
    {
      "MuaTM": 27308,
      "MuaCK": 27208,
      "BanTM": 27372,
      "BanCK": 27572,
      "LoaiTien": "GBP",
      "Nhom": ""
    },
    {
      "MuaTM": 1,
      "MuaCK": 23538,
      "BanTM": 1,
      "BanCK": 23653,
      "LoaiTien": "CHF",
      "Nhom": ""
    },
    {
      "MuaTM": 17535,
      "MuaCK": 1,
      "BanTM": 17593,
      "BanCK": 1,
      "LoaiTien": "CAD",
      "Nhom": "TM"
    }
  ]
}"""

from datetime import datetime, timedelta

past = datetime.now() + timedelta(days=30)
# present = datetime.now()
# print(past < present)
# print(past)
# print(present)
# print(datetime(3000, 1, 1) < present)
# print(present - datetime(2000, 4, 4))
#
#
# exp = "2020-08-31"

if (datetime.strptime(str(past.date()), "%Y-%m-%d") - timedelta(days=30)).date() == datetime.now().date():
    print("Yes")
