"""empty message

Revision ID: 48fa6f5baa98
Revises: 
Create Date: 2023-06-06 14:00:36.264626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fa6f5baa98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SchedulerManager',
    sa.Column('Id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SchedulerManager')
    # ### end Alembic commands ###
